# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sap_db2_user: 'db2{{ sap_nw_sid | lower }}'
sap_db2_state_dir: /db2/{{ sap_db2_user }}/.ansible-state
sap_db2_sid: '{{ sap_nw_db_sid }}'

sap_nw_master_password: '{{ sap_nw_password }}'
sap_nw_sapadm_password: '{{ sap_nw_password }}'
sap_nw_sapsid_password: '{{ sap_nw_password }}'
sap_nw_sidadm_password: '{{ sap_nw_password }}'
sap_db2_dbsid_password: '{{ sap_nw_password }}'
sap_nw_user: '{{ sap_nw_sid | lower }}adm'

sap_db2_sysadm_gid: 2002
sap_db2_sysctrl_gid: 2003
sap_db2_sysmaint_gid: 2004
sap_db2_sysmon_gid: 2005
sap_sapsys_gid: 2626
sap_nw_sidadm_uid: 2000
sap_nw_sapadm_uid: 2001
sap_nw_sapsid_uid: 2002
sap_db2_dbsid_uid: 2003

sap_nw_ascs_instance_number: '01'
sap_nw_pas_instance_number: '00'
sap_nw_ascs_virtual_host: '{{ ansible_hostname }}'
sap_nw_pas_virtual_host: '{{ ansible_hostname }}'
sap_nw_install_files_dest: /sapmnt/Software
sap_nw_kernel_files: '{{ sap_nw_install_files_dest }}/Kernel_Files'
sap_nw_rdbms_files: '{{ sap_nw_install_files_dest }}/RDBMS'

sap_nw_ascs_install_gateway: false
sap_nw_ascs_install_web_dispatcher: false

sap_db2_sid_partition_name: db2
sap_db2_sid_mountpoint: /db2/{{ sap_db2_sid }}
sap_db2_db2sid_partition_name: db2sid
sap_db2_db2sid_mountpoint: /db2/db2{{ sap_db2_sid }}
sap_db2_log_archive_partition_name: db2logarchive
sap_db2_log_archive_mountpoint: /db2/{{ sap_db2_sid }}/log_archive
sap_db2_log_partition_name: db2log
sap_db2_log_mountpoint: /db2/{{ sap_db2_sid }}/log_dir
sap_db2_dump_partition_name: db2dump
sap_db2_dump_mountpoint: /db2/{{ sap_db2_sid }}/db2dump
sap_db2_sapdata_partition_name: db2sapdata
sap_db2_sapdata_mountpoint: /db2/{{ sap_db2_sid }}/sapdata/sapdata1
sap_db2_saptmp_partition_name: db2saptmp
sap_db2_saptmp_mountpoint: /db2/{{ sap_db2_sid }}/saptmp/saptmp1
sap_swap_partition_name: swap
sap_swap_mountpoint: /SWAP
# sap_usrsap_partition_name: saplv1
sap_usrsap_mountpoint: /usr/sap/{{ sap_db2_sid }}
# sap_sapmnt_partition_name: saplv2
sap_sapmnt_sid_mountpoint: /sapmnt/{{ sap_db2_sid }}
sap_sapmnt_partition_name: sapmnt
sap_sapmnt_mountpoint: /sapmnt
sap_vg_name: sapvg

sap_nw_disks:
- name: swap
  partition_path: "{{ sap_swap_partition_name }}"
- name: saplv1
  partition_path: "{{ sap_vg_name }}"
- name: saplv2
  partition_path: "{{ sap_vg_name }}"
- name: sapmnt
  partition_path: "{{ sap_sapmnt_partition_name }}"
- name: db2
  partition_path: "{{ sap_db2_sid_partition_name }}"
- name: db2sid
  partition_path: "{{ sap_db2_db2sid_partition_name }}"
- name: db2logarchive
  partition_path: "{{ sap_db2_log_archive_partition_name }}"
- name: db2dump
  partition_path: "{{ sap_db2_dump_partition_name }}"
- name: db2log
  partition_path: "{{ sap_db2_log_partition_name }}"
- name: db2sapdata
  partition_path: "{{ sap_db2_sapdata_partition_name }}"
- name: db2saptmp
  partition_path: "{{ sap_db2_saptmp_partition_name }}"

sap_nw_logvols:
  swap:
    size: 100%VG
    vol: "{{ sap_swap_partition_name }}" 
    mountpoint: "{{ sap_swap_mountpoint }}"
    fstype: swap
  saplv1:
    size: 50%VG
    vol: "{{ sap_vg_name }}"
    mountpoint: "{{ sap_usrsap_mountpoint }}"
    fstype: xfs
  saplv2:
    size: 50%VG
    vol: "{{ sap_vg_name }}"
    mountpoint: "{{ sap_sapmnt_sid_mountpoint }}"
    fstype: xfs
  sapmnt:
    size: 100%VG
    vol: "{{ sap_sapmnt_partition_name }}"
    mountpoint: "{{ sap_sapmnt_mountpoint }}"
    fstype: xfs
  db2:
    size: 100%VG
    vol: "{{ sap_db2_sid_partition_name }}"
    mountpoint: "{{ sap_db2_sid_mountpoint }}"
    fstype: xfs
  db2sid:
    size: 100%VG
    vol: "{{ sap_db2_db2sid_partition_name }}"
    mountpoint: "{{ sap_db2_db2sid_mountpoint }}"
    fstype: xfs
  db2logarchive:
    size: 100%VG
    vol: "{{ sap_db2_log_archive_partition_name }}"
    mountpoint: "{{ sap_db2_log_archive_mountpoint }}"
    fstype: xfs
  db2dump:
    size: 100%VG
    vol: "{{ sap_db2_dump_partition_name }}"
    mountpoint: "{{ sap_db2_dump_mountpoint }}"
    fstype: xfs
  db2log:
    size: 100%VG
    vol: "{{ sap_db2_log_partition_name }}"
    mountpoint: "{{ sap_db2_log_mountpoint }}"
    fstype: xfs
  db2sapdata:
    size: 100%VG
    vol: "{{ sap_db2_sapdata_partition_name }}"
    mountpoint: "{{ sap_db2_sapdata_mountpoint }}"
    fstype: xfs
  db2saptmp:
    size: 100%VG
    vol: "{{ sap_db2_saptmp_partition_name }}"
    mountpoint: "{{ sap_db2_saptmp_mountpoint }}"
    fstype: xfs

sap_db2_product: 'DB2'
# sap_db2_product_version: '11.5MP5FP1'
sap_db2_product_version: '12.1MP1FP0'
sap_db2_product_and_version: '{{ sap_db2_product }}/{{ sap_db2_product_version }}'
sap_nw_product: 'NetWeaver'
sap_nw_product_version: '750'
sap_nw_product_and_version: '{{ sap_nw_product }}/{{ sap_nw_product_version }}'
sap_product_vars:
  'NetWeaver/750':
    # onehost_product_id: 'NW_ABAP_OneHost:NW750.DB6.ABAP'
    onehost_product_id: 'NW_ABAP_OneHost:BS2016.ERP608.DB6.PD'
    swpm_path: '{{ sap_nw_install_files_dest }}/SWPM1.0'
    load_files: '{{ sap_nw_install_files_dest }}/NW75'
    install_files: [Kernel_Files, NW75, SWPM1.0]
    ensa_version: '1'
  'DB2/10.5FP9':
    db_client: '{{ sap_nw_install_files_dest }}/DB_CLIENT'
    install_files: [DB_CLIENT, RDBMS]
  'DB2/11.1MP4FP6':
    db_client: '{{ sap_nw_install_files_dest }}/DB_CLIENT'
    install_files: [DB_CLIENT, RDBMS]
  'DB2/11.5MP5FP1':
    db_client: '{{ sap_nw_install_files_dest }}/DB_CLIENT'
    install_files: [DB_CLIENT, RDBMS]
  'DB2/12.1MP1FP0':
    db_client: '{{ sap_nw_install_files_dest }}/DB_CLIENT'
    install_files: [DB_CLIENT, RDBMS]